web/Controllers/ResourceController.cs
/*
 *
 * (c) Copyright Ascensio System Limited 2010-2015
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *
 * You can contact Ascensio System SIA by email at sales@onlyoffice.com
 *
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Resources;
using System.Text;
using System.Web.Mvc;
using Newtonsoft.Json;
using OneClickInstallation.Helpers;
using OneClickInstallation.Resources;

namespace OneClickInstallation.Controllers
{
    public class ResourceController : Controller
    {

        public ActionResult Index(string culture)
        {
            if (string.IsNullOrWhiteSpace(culture))
            {
                culture = System.Threading.Thread.CurrentThread.CurrentCulture.TwoLetterISOLanguageName;
            }

            if (!ClientCacheEmpty()) return NotModifiedResponse();

            var cachedScript = CacheHelper.GetJsResuorce(culture);

            if (cachedScript != null) return ScriptResponse(cachedScript);

            var resources = new List<Tuple<ResourceManager, string>>
                {
                    new Tuple<ResourceManager, string>(OneClickJsResource.ResourceManager, typeof (OneClickJsResource).Name)
                };

            var script = CreateResourcesScript(resources, culture);

            CacheHelper.SetJsResuorce(culture, script);

            return ScriptResponse(script);
        }


        private bool ClientCacheEmpty()
        {
            return (Request.Headers["If-Modified-Since"] == null);
        }

        private ContentResult NotModifiedResponse()
        {
            Response.StatusCode = 304;
            Response.StatusDescription = "Not Modified";
            return Content(string.Empty);
        }

        private JavaScriptResult ScriptResponse(string script)
        {
            Response.Cache.SetLastModified(DateTime.UtcNow);
            return new JavaScriptResult { Script = script };
        }

        private static string CreateResourcesScript(IEnumerable<Tuple<ResourceManager, string>> resources, string culture)
        {
            var script = string.Empty;
            foreach (var pair in resources)
            {
                var baseSet = pair.Item1.GetResourceSet(CultureInfo.InvariantCulture, true, true);
                var js = new StringBuilder(pair.Item2 + "={");
                foreach (DictionaryEntry entry in baseSet)
                {
                    var key = (string)entry.Key;
                    var value = pair.Item1.GetString(key, new CultureInfo(culture)) ?? string.Empty;
                    js.AppendFormat("\"{0}\":{1},", entry.Key, JsonConvert.SerializeObject(value));
                }

                script += js.ToString();
                if (!string.IsNullOrEmpty(script))
                {
                    script = script.Remove(script.Length - 1);
                }
                script += "};";
            }

            return script;
        }
    }
}

web/Views/Shared/_FooterPartial.cshtml
@using OneClickInstallation.Resources

<div class="layout-content-wrapper clear-fix">
    <div class="copyright">
        @String.Format(OneClickCommonResource.Copyright, DateTime.Now.Year)
    </div>

    <div class="social-links clear-fix">
        <span class="uppercase">@OneClickCommonResource.FollowUs</span>
        <ul>
            <li>
                <a class="facebook" title="@OneClickCommonResource.Facebook" target="_blank" href="https://www.facebook.com/pages/OnlyOffice/833032526736775"></a>
            </li>
            <li>
                <a class="twitter" title="@OneClickCommonResource.Twitter" target="_blank" href="https://twitter.com/ONLY_OFFICE"></a>
            </li>
            <li>
                <a class="linkedin" title="@OneClickCommonResource.LinkedIn" target="_blank" href="https://www.linkedin.com/groups?home=&gid=6726380&trk"></a>
            </li>
            <li>
                <a class="google" title="@OneClickCommonResource.Google" target="_blank" href="https://plus.google.com/+teamlab/"></a>
            </li>
            <li>
                <a class="youtube" title="@OneClickCommonResource.YouTube" target="_blank" href="http://www.youtube.com/TeamLabdotcom"></a>
            </li>
            <li>
                <a class="vk" title="@OneClickCommonResource.VK" target="_blank" href="http://vk.com/onlyoffice"></a>
            </li>
        </ul>
    </div>
</div>

web/Views/Shared/_HeaderPartial.cshtml
@using OneClickInstallation.Resources

@{
    var currentAction = ViewContext.RouteData.Values["action"].ToString().ToLower();
    var currentLang = System.Threading.Thread.CurrentThread.CurrentCulture.TwoLetterISOLanguageName;
}

<div class="layout-content-wrapper clear-fix">
    <a class="logo" href="@Url.Action("Index")"></a>

    <div class="lang-switcher">
        <div class="switcher">
            <div class="lang-title @currentLang">
                <span>@LangHelper.GetLangTitle(currentLang)</span>
            </div>
        </div>
        <div class="action-menu">
            <div class="corner"></div>
            <ul>
                @foreach (var lang in LangHelper.GetLanguages())
                {
                    <li class="action">
                        <a href="@Url.Action(currentAction, new {lang})" class="@lang">
                            @LangHelper.GetLangTitle(lang)
                        </a>
                    </li>
                }
            </ul>
        </div>
    </div>

    <div class="top-header-nav">
        <a href="@Url.Action("Index")" class="white uppercase selected">
            @OneClickHomePageResource.Home
        </a>

        <a href="@string.Format("http://helpcenter.onlyoffice.com/{0}server/docker/oneclickinstall/faq.aspx", String.Equals(currentLang, "en", StringComparison.OrdinalIgnoreCase) ? "" : currentLang + "/")"
            target="_blank" class="white uppercase">
            @OneClickHomePageResource.FAQ
        </a>

        <a href="@string.Format("http://www.onlyoffice.com/{0}/about.aspx", currentLang)" target="_blank" class="white uppercase">
            @OneClickCommonResource.About
        </a>
    </div>
</div>

web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <meta name="keywords" content="@OneClickCommonResource.MetaKeywords">
    <meta name="description" content="@OneClickCommonResource.MetaDescription">
    
    <title>@ViewBag.Title</title>
    
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:900,800,700,600,500,400,300&amp;subset=latin,cyrillic-ext,cyrillic,latin-ext">
    
    @Styles.Render("~/Content/less")

    @if (!string.IsNullOrEmpty(Settings.AnalyticsFileUrl))
    {
        <script src="@Settings.AnalyticsFileUrl"></script>
    }

</head>
    <body>
        
        <div class="layout-wrapper">
            
            <div class="layout-header">
                @Html.Partial("_HeaderPartial")
            </div>
            
            <div class="layout-body layout-content-wrapper clear-fix">

                @if (IsSectionDefined("leftSide"))
                {
                    <div class="layout-left-side">
                        @RenderSection("leftSide", false)
                    </div>
                }

                @if (IsSectionDefined("rightSide"))
                {
                    <div class="layout-right-side">
                        @RenderSection("rightSide", false)
                    </div>
                }
                
                @RenderBody()

            </div>

            <div class="layout-footer">
                @Html.Partial("_FooterPartial")
            </div>

        </div>

        <script src="@Url.Action("Index", "Resource")"></script>
        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", false)

    </body>
</html>